CoursePlannerApp/views/course_views.py
from flask import Blueprint, redirect, render_template, flash, render_template, request, url_for
from flask_login import current_user, login_required
from werkzeug.local import LocalProxy
from CoursePlannerApp.dbmanager import get_db
import oracledb
from CoursePlannerApp.objects.course import CourseForm, Course
from CoursePlannerApp.objects.element import Element, ElementFormBridge

bp = Blueprint('courses', __name__, url_prefix='/courses')

dtb = LocalProxy(get_db)

#Get * Courses 
@bp.route("/")
def get_courses():
    if request.method == 'GET':
        try:
            courses = dtb.get_courses()
            domains = dtb.get_domains() 
        except Exception as e:
            flash('There is an issue with the Database')
        if not courses or len(courses) == 0:
            flash('There is no course in database')            
        return render_template('courses.html', courses = courses, domains=domains)
    
@bp.route("/<course_id>/", methods=['GET', 'POST'])
def list_competencies(course_id):
    if request.method == 'GET':
        try:
            course = dtb.get_course(course_id)
            competencies = dtb.get_course_competencies(course_id) 
            elements_covered=dtb.get_elements_covered_by_a_course(course_id)
            domains = dtb.get_domains() 
        except Exception as e:
            flash('There is an issue with the Database')
        if not competencies or len(competencies) == 0:
            flash('There is no competency in the database')            
    return render_template('course.html', competencies = competencies, course = course, domains = domains, elements_covered = elements_covered)

@bp.route('/<course_id>/new/', methods=['GET', 'POST'])
@login_required
def add_element_for_course(course_id):
    form = ElementFormBridge()
    #Fill element drop list
    try:
        elements = dtb.get_elements()
    except Exception:
        flash('There is an issue with the Database')
        
    form.id.choices = sorted([(element.id, str(element.id)+" - "+element.name) for element in elements]) #Getting data for Select field for competencyId  (Circular import error)
    form.id.choices.insert(0, [0, "Choose an Element of Competency"])
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                dtb.add_element_course_bridging(int(form.id.data),course_id,int(form.element_hours.data))
                flash("Element was created successfully.")
                hour_validator(course_id)
                return redirect(url_for('courses.list_competencies',course_id=course_id))
            
            except oracledb.IntegrityError as e:
                error_obj, = e.args #To acces code error 
                if error_obj.code == 1: # 1 is related to primary key issue (when the primary key already exist) 
                    flash("Element already exist")
            
            except Exception as e:
                flash('There is an issue with the Database')

    return render_template('Add/addCourseElementBridge.html', form=form)

#Add course
@bp.route('/new/', methods=['GET', 'POST'])
@login_required
def create_course():
    form = CourseForm()   
    #Fill term drop list
    form.termId.choices = sorted([(term.id, str(term.id)+" - "+term.name) for term in dtb.get_terms()]) #Getting data for Select field for termId  (Circular import error)
    form.termId.choices.insert(0, [0, "Choose a term"])

    
    #Fill domain drop list
    form.domainId.choices = sorted([(domain.id, str(domain.id)+" - "+domain.name) for domain in dtb.get_domains()]) #Getting data for Select field for domainId  (Circular import error)
    form.domainId.choices.insert(0, [0, "Choose a domain"])
    
    if request.method == 'POST':
        if form.validate_on_submit():
            
            newCourse = Course(form.id.data, form.name.data, form.description.data, 
                               form.termId.data, form.domainId.data, 
                               form.lab_hours.data, form.theory_hours.data, 
                               form.work_hours.data)
            
            for course in dtb.get_courses():
                if(newCourse.id == course.id or newCourse.name == course.name):
                    flash("Course already exists!")
                    return redirect(url_for('courses.get_courses'))
            
            try:
                dtb.add_course(newCourse)
                flash("Course has been added")
                hour_validator(form.id.data)    
                return redirect(url_for('courses.list_competencies',course_id=form.id.data))
            
            except oracledb.IntegrityError as e:
                error_obj, = e.args #To acces code error 
                if error_obj.code == 1: # 1 is related to primary key issue (when the primary key already exist) 
                    flash("Course already exist")
        
            except Exception as e:
                flash("Error: " + str(e))
                
    return render_template('Add/addCourse.html', form=form)


#Update course
@bp.route('/<course_id>/update/', methods=['GET', 'POST'])
@login_required
def update_course(course_id):
    #Cheack if course exist
    try:
        course = dtb.get_course(course_id)
    except Exception as e:
        flash("Error: "+ str(e))
    
    if course is None:
        flash("Course not found")
        return redirect(url_for('courses.get_courses'))
    
    
    form = CourseForm(obj=course) #Prefill the form
      
    #Creating a new one based on the updated form
    #Fill term drop list
    try:
        terms = dtb.get_terms()
        domains = dtb.get_domains()
    except Exception:
        flash("")
    form.termId.choices = sorted([(term.id, str(term.id)+" - "+term.name) for term in terms]) #Getting data for Select field for termId  (Circular import error)
    form.termId.choices.insert(0, [0, "Choose a term"])

    #Fill domain drop list
    form.domainId.choices = sorted([(domain.id, str(domain.id)+" - "+domain.name) for domain in domains]) #Getting data for Select field for domainId  (Circular import error)
    form.domainId.choices.insert(0, [0, "Choose a domain"])
    
    if request.method == 'POST':
        if form.validate_on_submit():
            
            updatedCourse = Course(form.id.data, form.name.data, form.description.data, 
                               form.termId.data, form.domainId.data, 
                               form.lab_hours.data, form.theory_hours.data, 
                               form.work_hours.data)
            
            # for course in dtb.get_courses():
            #     if( updatedCourse.id == course.id or updatedCourse.name == course.name):
            #         flash("Course already exists!")
                
            try:
                dtb.update_course(updatedCourse)
                flash("Course has been updated")    
                return redirect(url_for('courses.get_courses'))      
            except Exception as e:
                flash("Error: " + str(e))
                
    return render_template('Update/updateCourse.html', form=form, course=course)

#Delete
@bp.route("/<course_id>/delete/", methods=["GET"])
@login_required
def delete(course_id):
    # try to delete course
    try:
        dtb.delete_course(course_id)
    except oracledb.Error as e:
        flash("Error: " + str(e))
        return redirect(url_for(".get_courses"))

    flash("Course deleted successfully")
    return redirect(url_for('courses.get_courses'))

#Delete an element for specific course
@bp.route('/<course_id>/<int:element_id>/delete/', methods=['GET'])
@login_required
def delete_element_for_course(course_id,element_id):
    try:
        dtb.delete_element_course_bridging(element_id,course_id)
        flash("Element deleted for this course successfully")
        hour_validator(course_id)
    except Exception as e:
        flash("Could not access the record")
        flash("Error: " + str(e))
        return redirect(url_for('courses.list_competencies',course_id=course_id))
    return redirect(url_for('courses.list_competencies',course_id=course_id))

def hour_validator(course_id):
    course=dtb.get_course(course_id)
    total_hours=(course.lab_hours + course.theory_hours) * 15
    current_hours=dtb.get_sum_hours(course_id)
    diff=total_hours-current_hours
    if(diff<0):
        flash(f'You must remove {diff*-1} hours to match {total_hours} hours of {course.name}')
    elif(diff>0):
        flash(f'You must add {diff} hours to match {total_hours} hours of {course.id} {course.name}')

CoursePlannerApp/views/domain_views.py
from flask import Blueprint, redirect, render_template, flash, render_template, request, url_for
from flask_login import login_required
from werkzeug.local import LocalProxy
from CoursePlannerApp.dbmanager import get_db
import oracledb

from CoursePlannerApp.objects.domain import DomainForm, Domain

bp = Blueprint('domains', __name__, url_prefix='/domains')

dtb = LocalProxy(get_db)

#Get * Domains
@bp.route("/")
def get_domains():
    if request.method == 'GET':
        try:
            domains = dtb.get_domains() 
        except Exception as e:
            flash('There is an issue with the Database')
        if not domains or len(domains) == 0:
            flash('There is no course in database')            
        return render_template('domains.html',domains=domains)

@bp.route("/<int:domain_id>/")
def get_domain(domain_id):
    if request.method == 'GET':
        try:
            domain = dtb.get_domain(domain_id) 
        except Exception as e:
            flash('There is an issue with the Database')
        if not domain:
            flash('There is no course in database')            
        return render_template('domain.html', domain=domain)


#Add Domain
@bp.route('/new/', methods=['GET', 'POST'])
@login_required
def create_domain():
    form = DomainForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            
            newDomain = Domain(form.id.data, form.name.data, form.description.data)
            
            for domain in dtb.get_domains():
                if(newDomain.id == domain.id or newDomain.name == domain.name):
                    flash("Domain already exists!")
                
            try:
                dtb.add_domain(newDomain)
                return redirect(url_for('domains.get_domains'))
            
            except oracledb.IntegrityError as e:
                error_obj, = e.args #To acces code error 
                if error_obj.code == 1: # 1 is related to primary key issue (when the primary key already exist) 
                    flash("Domain already exist")
        
            except Exception as e:
                flash("Error: " + str(e))
        else:
            flash('Invalid input')
    return render_template('Add/addDomain.html', form=form)

#Update Domain
@bp.route('/<int:domain_id>/update/', methods=['GET', 'POST'])
@login_required
def update_domain(domain_id):
    
    #Check if domain exist
    try:
        domain = dtb.get_domain(domain_id)
    except Exception as e:
        flash("Error: "+ str(e))
    
    if domain is None:
        flash("Domain not found")
        return redirect(url_for('domains.get_domains'))
    
    form = DomainForm(obj=domain) #Prefill the form
    
    if request.method == 'POST':
        if form.validate_on_submit():

            updatedDomain = Domain(form.id.data, form.name.data, form.description.data)

            for domain in dtb.get_domains():
                if(updatedDomain.id == domain.id or updatedDomain.name == domain.name):
                    flash("Domain already exists!")

            try:
                dtb.update_domain(updatedDomain)
                flash("Domain has been updated")    
                return redirect(url_for('domains.get_domains'))
            except Exception as e:
                flash("Error: " + str(e))

    return render_template('Update/updateDomain.html', form=form, domain=domain)

#Delete
@bp.route("/<domain_id>/delete/", methods=["GET"])
@login_required
def delete(domain_id):

    try:
        courseImpacted = dtb.get_courses_in_domain(domain_id) 
    except Exception as e:
        flash("Could not acces the domain")
        flash("Error: " + str(e))
        return redirect(url_for('domains.get_domains'))

    # try to delete domain
    try:
        dtb.delete_domain(domain_id)
        flash("Domain deleted successfully")
    except oracledb.Error as e:
        flash("You can't delete this domain until you delete the following courses or change their domains")
        courseImpactedString = ""
        for course in courseImpacted:
            courseImpactedString = f'-- {course.name} --'+ courseImpactedString
        flash(courseImpactedString)
    except Exception as e:
        flash("Error: " + str(e))
        return redirect(url_for("domains.get_domains"))

    return redirect(url_for('domains.get_domains'))

CoursePlannerApp/views/term_views.py
from flask import Blueprint, render_template, flash, render_template, request, redirect, url_for
from flask_login import login_required
from werkzeug.local import LocalProxy
from CoursePlannerApp.dbmanager import get_db
import oracledb

from CoursePlannerApp.objects.term import TermForm, Term

bp = Blueprint('terms', __name__, url_prefix='/terms')

dtb = LocalProxy(get_db)

#Get * Terms
@bp.route("/")
def get_terms():
    try:
        terms = dtb.get_terms()
    except Exception as e:
        flash("Error: " + str(e))
        return render_template("terms.html", terms=[])
    
    terms.sort(key=lambda x: x.id)
    
    if not terms or len(terms) == 0:
        flash('There is no term in database')
        return render_template('display.html')
    return render_template('terms.html', terms = terms)

#Add term
@bp.route('/new/', methods=['GET', 'POST'])
@login_required
def create_term():
    form = TermForm()
    if request.method == 'POST':
        if form.validate_on_submit():

            newTerm = Term(form.id.data, form.name.data)
            try:
                dtb.add_term(newTerm)
                return redirect(url_for('terms.get_terms'))

            except oracledb.IntegrityError as e:
                error_obj, = e.args #To acces code error
                if error_obj.code == 1: # 1 is related to primary key issue (when the primary key already exist)
                    flash("Course already exist")

            except Exception as e:
                flash("Error: " + str(e))
        else:
            flash('Invalid input')
    return render_template('Add/addTerm.html', form=form)

#Update term
@bp.route('/<term_id>/update/', methods=['GET', 'POST'])
@login_required
def update_term(term_id):

    #Check if term exist
    try:
        term = dtb.get_term(term_id)
    except Exception as e:
        flash("Error: "+ str(e))

    if term is None:
        flash("Term not found")
        return redirect(url_for('terms.get_terms'))

    form = TermForm(obj=term) #Prefill the form

    if request.method == 'POST':
        if form.validate_on_submit():

            updatedTerm = Term(term_id, form.name.data)
            try:
                dtb.update_term(updatedTerm)
                flash("Term has been updated")
                return redirect(url_for('terms.get_terms'))
            except Exception as e:
                flash("Error: " + str(e))

    return render_template('Update/updateTerm.html', form=form, term=term)

#Delete
@bp.route("/<term_id>/delete/", methods=["GET"])
@login_required
def delete(term_id):

    try:
        courseImpacted = dtb.get_courses_in_term(term_id)
    except Exception as e:
        flash("Could not acces the term")


    # try to delete term
    try:
        dtb.delete_term(term_id)
        flash("Term deleted successfully")
    except oracledb.Error as e:
        flash("You can't delete this term until you delete the following courses or change their domains")
        courseImpactedString = ""
        for course in courseImpacted:
            courseImpactedString = f'-- {course.name} --'+ courseImpactedString
        flash(courseImpactedString)
    except Exception as e:
        flash("Error: " + str(e))
        return redirect(url_for("terms.get_terms"))

    return redirect(url_for("terms.get_terms"))

CoursePlannerApp/templates/Add/add.html
{% extends 'base.html' %}
{% block title %}
    Add Page
{% endblock %}
{% block headerTitle %}
    Use the buttons below to add something new to the database
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='add.css')}}"/>
{% endblock %}
{% block content%}
    <div class="add-options">
        <a href="{{url_for('courses.create_course')}}"><button>Add a new course</button></a>
        <a href="{{url_for('competencies.create_competency')}}"><button>Add a new competency</button></a>
        <a href="{{url_for('doamins.create_domain')}}"><button>Add a new domain</button></a>
        <a href="{{url_for('elements.create_element')}}"><button>Add a new element of competency</button></a>
        <a href="{{url_for('terms.create_term')}}"><button>Add a new term</button></a>
    </div>
{% endblock%}

CoursePlannerApp/templates/Add/addCompetency.html
{% extends 'base.html' %}
{% block title %}
    Add Competency
{% endblock %}
{% block headerTitle %}
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='add.css')}}"/>
{% endblock %}
{% block content%}
    <h1>New Competency:</h1>
    <form method="post">
        {{ form.csrf_token }}
        {{ form.id.label }}              {{ form.id() }}
        {{ form.name.label }}            {{ form.name() }}
        {{ form.achievement.label }}     {{ form.achievement() }}
        {{ form.type.label }}            {{ form.type() }}
        <button type="submit" id="addCompetency" name="addCompetency"> Submit </button>
    </form>
{% endblock%}

CoursePlannerApp/templates/Add/addCourse.html
{% extends 'base.html' %}
{% block title %}
    Add Course
{% endblock %}
{% block headerTitle %}
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='add.css')}}"/>
{% endblock %}
{% block content%}
    <h1>New Course:</h1>
    <form method="post">
        {{ form.csrf_token }}
        {{ form.id.label }}              {{ form.id() }}             <div class="error">{{ form.id.errors[0]}}</div>
        {{ form.name.label }}            {{ form.name() }}           <div class="error">{{ form.id.errors[0]}}</div>
        {{ form.description.label }}     {{ form.description() }}
        {{ form.termId.label }}          {{ form.termId() | safe}}
        {{ form.domainId.label }}        {{ form.domainId() }}
        {{ form.theory_hours.label }}    {{ form.theory_hours() }}
        {{ form.lab_hours.label }}       {{ form.lab_hours() }}
        {{ form.work_hours.label }}      {{ form.work_hours() }}
        <button type="submit" id="addCourse" name="addCourse"> Submit </button>
    </form>
{% endblock%}

CoursePlannerApp/templates/Add/addCourseElementBridge.html
{% extends 'base.html' %}
{% block title %}
    Add an Element for thic course
{% endblock %}
{% block headerTitle %}
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='add.css')}}"/>
{% endblock %}
{% block content%}
    <h1>Choose your Element:</h1>
    <form method="post">
        {{ form.csrf_token }}
        {{ form.id.label }}             {{ form.id() }}
        {{ form.element_hours.label }}  {{ form.element_hours() }}
        <button type="submit" id="addElement" name="addElement"> Submit </button>
    </form>
{% endblock%}

CoursePlannerApp/templates/Add/addDomain.html
{% extends 'base.html' %}
{% block title %}
    Add Domain
{% endblock %}
{% block headerTitle %}
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='add.css')}}"/>
{% endblock %}
{% block content%}
    <h1>New Domain:</h1>
    <form method="post">
        {{ form.csrf_token }}
        {{ form.id.label }}              {{ form.id() }}
        {{ form.name.label }}            {{ form.name() }}
        {{ form.description.label }}     {{ form.description() }}
        <button type="submit" id="addDomain" name="addDomain"> Submit </button>
    </form>
{% endblock%}

CoursePlannerApp/templates/Add/addElement.html
{% extends 'base.html' %}
{% block title %}
    Add Element
{% endblock %}
{% block headerTitle %}
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='add.css')}}"/>
{% endblock %}
{% block content%}
    <h1>New Element:</h1>
    <form method="post">
        {{ form.csrf_token }}
        <!-- {{ form.id.label}}              {{ form.id() }} -->
        {{ form.order.label}}           {{ form.order() }}
        {{ form.name.label}}            {{ form.name() }}
        {{ form.criteria.label}}        {{ form.criteria() }}
        {{ form.competencyId.label}}    {{ form.competencyId() }}
        <button type="submit" id="addElement" name="addElement"> Submit </button>
    </form>
{% endblock%}

CoursePlannerApp/templates/Add/addEntities.html
{% extends 'base.html' %}
{% block title %}
    Add
{% endblock %}
{% block headerTitle %}
    Choose the entity to add
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='add.css')}}"/>
{% endblock %}
{% block content%}
    <button type="button" id="addCourses" name="addCourses" ><a href="{{url_for('courses.create_course')}}"> COURSES </a></button>
    <button type="button" id="addTerms" name="addTerms" > <a href="{{url_for('terms.create_term')}}"> TERMS  </a> </button>
    <button type="button" id="addDomains" name="addDomains"> <a href="{{url_for('domains.create_domain')}}"> DOMAINS</a> </button>
    <button type="button" id="addElements" name="addElements"> <a href="{{url_for('elements.create_element')}}"> ELEMENTS </a> </button>
    <button type="button" id="addCompetencies" name="addCompetencies"> <a href="{{url_for('competencies.create_competency')}}"> COMPETENCIES </a> </button>
{% endblock%}

CoursePlannerApp/templates/Add/addTerm.html
{% extends 'base.html' %}
{% block title %}
    Add Term
{% endblock %}
{% block headerTitle %}
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='add.css')}}"/>
{% endblock %}
{% block content%}
    <h1>New Term:</h1>
    <form method="post">
        {{ form.csrf_token }}
        {{ form.id.label }}              {{ form.id() }}
        {{ form.name.label }}            {{ form.name() }}
        <button type="submit" id="addTerm" name="addTerm"> Submit </button>
    </form>
{% endblock%}