CoursePlannerApp/views/competency_views.py
from flask_login import login_required
import oracledb
from flask import Blueprint, flash, render_template, request, url_for, redirect
from werkzeug.local import LocalProxy
from CoursePlannerApp.dbmanager import get_db
from CoursePlannerApp.objects.competency import CompetencyForm, Competency

bp = Blueprint("competencies", __name__, url_prefix="/competencies")

dtb = LocalProxy(get_db)

#Get * Competencies
@bp.route("/")
def get_competencies():
    try:
        competencies = dtb.get_competencies()
    except oracledb.Error as e:
        flash("Error: " + str(e))
        return render_template("competencies.html", banner=[])

    if not competencies or len(competencies) == 0:
        flash("There are no competency in database")
    return render_template("competencies.html", competencies=competencies)

@bp.route("/<competency_id>/", methods=['GET', 'POST'])
def list_elements(competency_id):
    if request.method == 'GET':
        try:
            competency = dtb.get_competency(competency_id)
            elements = dtb.get_competency_elements(competency_id) 
        except Exception as e:
            flash('There is an issue with the Database')
        if not elements or len(elements) == 0:
            flash('There is no competency in the database')            
    return render_template('competency.html', elements = elements,competency=competency)

#Add Competency
@bp.route('/new/', methods=['GET', 'POST'])
@login_required
def create_competency():
    form = CompetencyForm()
    if request.method == 'POST':
        if form.validate_on_submit():

            newCompetency = Competency(form.id.data, form.name.data, form.achievement.data, 
                                       form.type.data)

            try:
                competencies = dtb.get_competencies() 
            except Exception:
                flash('There is an issue with the Database')
                
            for competency in competencies:
                if(newCompetency.id == competency.id or newCompetency.name == competency.name):
                    flash("Competency already exists!")
            
            try:
                dtb.add_competency(newCompetency)
                return redirect(url_for('competencies.get_competencies'))
            
            except oracledb.IntegrityError as e:
                error_obj, = e.args #To acces code error 
                if error_obj.code == 1: # 1 is related to primary key issue (when the primary key already exist) 
                    flash("Competency already exist")
        
            except Exception as e:
                flash("Error: " + str(e))
        else:
            flash('Invalid input')
    return render_template('Add/addCompetency.html', form=form)

#Update competency
@bp.route('/<competency_id>/update/', methods=['GET', 'POST'])
@login_required
def update_competency(competency_id):
    oldCompetencyId = competency_id
    #Check if competency exist
    try:
        competency = dtb.get_competency(competency_id)
    except Exception as e:
        flash("Error: "+ str(e))
    
    if competency is None:
        flash("Competency not found")
        return redirect(url_for('competencies.get_competencies'))
    
    form = CompetencyForm(obj=competency) #Prefill the form
    
    if request.method == 'POST':
        if form.validate_on_submit():

            updatedCompetency = Competency(form.id.data, form.name.data, form.achievement.data, 
                                       form.type.data)
            
            for competency in dtb.get_competencies():
                if(updatedCompetency.id == competency.id or updatedCompetency.name == competency.name):
                    flash("Competency already exists!")
                
            try:
                dtb.update_competency(updatedCompetency, oldCompetencyId)
                flash("Competency has been updated")    
                return redirect(url_for('competencies.get_competencies'))
            except Exception as e:
                flash("Error: " + str(e))

    return render_template('Update/updateCompetency.html', form=form, competency=competency)
#Delete
@bp.route("/<competency_id>/delete/", methods=["GET"])
@login_required
def delete(competency_id):
    try:
        competency = dtb.get_competency(competency_id)
    except Exception as e:
        flash("Could not acces the competency")
        return redirect(url_for('competency.list_elements', competency_id=competency.id))
    
    # try to delete competency
    try:
        dtb.delete_competency(competency.id)
    except oracledb.Error as e:
        flash("Error: " + str(e))
        return redirect(url_for('competency.list_elements', 'competency_id=competency.id'))

    flash("Competency deleted successfully")
    return redirect(url_for('competencies.get_competencies'))

CoursePlannerApp/views/course_views.py
from flask import Blueprint, redirect, render_template, flash, render_template, request, url_for
from flask_login import current_user, login_required
from werkzeug.local import LocalProxy
from CoursePlannerApp.dbmanager import get_db
import oracledb
from CoursePlannerApp.objects.course import CourseForm, Course
from CoursePlannerApp.objects.element import Element, ElementFormBridge

bp = Blueprint('courses', __name__, url_prefix='/courses')

dtb = LocalProxy(get_db)

#Get * Courses 
@bp.route("/")
def get_courses():
    if request.method == 'GET':
        try:
            courses = dtb.get_courses()
            domains = dtb.get_domains() 
        except Exception as e:
            flash('There is an issue with the Database')
        if not courses or len(courses) == 0:
            flash('There is no course in database')            
        return render_template('courses.html', courses = courses, domains=domains)
    
@bp.route("/<course_id>/", methods=['GET', 'POST'])
def list_competencies(course_id):
    if request.method == 'GET':
        try:
            course = dtb.get_course(course_id)
            competencies = dtb.get_course_competencies(course_id) 
            elements_covered=dtb.get_elements_covered_by_a_course(course_id)
            domains = dtb.get_domains() 
        except Exception as e:
            flash('There is an issue with the Database')
        if not competencies or len(competencies) == 0:
            flash('There is no competency in the database')            
    return render_template('course.html', competencies = competencies, course = course, domains = domains, elements_covered = elements_covered)

@bp.route('/<course_id>/new/', methods=['GET', 'POST'])
@login_required
def add_element_for_course(course_id):
    form = ElementFormBridge()
    #Fill element drop list
    try:
        elements = dtb.get_elements()
    except Exception:
        flash('There is an issue with the Database')
        
    form.id.choices = sorted([(element.id, str(element.id)+" - "+element.name) for element in elements]) #Getting data for Select field for competencyId  (Circular import error)
    form.id.choices.insert(0, [0, "Choose an Element of Competency"])
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                dtb.add_element_course_bridging(int(form.id.data),course_id,int(form.element_hours.data))
                flash("Element was created successfully.")
                hour_validator(course_id)
                return redirect(url_for('courses.list_competencies',course_id=course_id))
            
            except oracledb.IntegrityError as e:
                error_obj, = e.args #To acces code error 
                if error_obj.code == 1: # 1 is related to primary key issue (when the primary key already exist) 
                    flash("Element already exist")
            
            except Exception as e:
                flash('There is an issue with the Database')

    return render_template('Add/addCourseElementBridge.html', form=form)

#Add course
@bp.route('/new/', methods=['GET', 'POST'])
@login_required
def create_course():
    form = CourseForm()   
    #Fill term drop list
    form.termId.choices = sorted([(term.id, str(term.id)+" - "+term.name) for term in dtb.get_terms()]) #Getting data for Select field for termId  (Circular import error)
    form.termId.choices.insert(0, [0, "Choose a term"])

    
    #Fill domain drop list
    form.domainId.choices = sorted([(domain.id, str(domain.id)+" - "+domain.name) for domain in dtb.get_domains()]) #Getting data for Select field for domainId  (Circular import error)
    form.domainId.choices.insert(0, [0, "Choose a domain"])
    
    if request.method == 'POST':
        if form.validate_on_submit():
            
            newCourse = Course(form.id.data, form.name.data, form.description.data, 
                               form.termId.data, form.domainId.data, 
                               form.lab_hours.data, form.theory_hours.data, 
                               form.work_hours.data)
            
            for course in dtb.get_courses():
                if(newCourse.id == course.id or newCourse.name == course.name):
                    flash("Course already exists!")
                    return redirect(url_for('courses.get_courses'))
            
            try:
                dtb.add_course(newCourse)
                flash("Course has been added")
                hour_validator(form.id.data)    
                return redirect(url_for('courses.list_competencies',course_id=form.id.data))
            
            except oracledb.IntegrityError as e:
                error_obj, = e.args #To acces code error 
                if error_obj.code == 1: # 1 is related to primary key issue (when the primary key already exist) 
                    flash("Course already exist")
        
            except Exception as e:
                flash("Error: " + str(e))
                
    return render_template('Add/addCourse.html', form=form)


#Update course
@bp.route('/<course_id>/update/', methods=['GET', 'POST'])
@login_required
def update_course(course_id):
    #Cheack if course exist
    try:
        course = dtb.get_course(course_id)
    except Exception as e:
        flash("Error: "+ str(e))
    
    if course is None:
        flash("Course not found")
        return redirect(url_for('courses.get_courses'))
    
    
    form = CourseForm(obj=course) #Prefill the form
      
    #Creating a new one based on the updated form
    #Fill term drop list
    try:
        terms = dtb.get_terms()
        domains = dtb.get_domains()
    except Exception:
        flash("")
    form.termId.choices = sorted([(term.id, str(term.id)+" - "+term.name) for term in terms]) #Getting data for Select field for termId  (Circular import error)
    form.termId.choices.insert(0, [0, "Choose a term"])

    #Fill domain drop list
    form.domainId.choices = sorted([(domain.id, str(domain.id)+" - "+domain.name) for domain in domains]) #Getting data for Select field for domainId  (Circular import error)
    form.domainId.choices.insert(0, [0, "Choose a domain"])
    
    if request.method == 'POST':
        if form.validate_on_submit():
            
            updatedCourse = Course(form.id.data, form.name.data, form.description.data, 
                               form.termId.data, form.domainId.data, 
                               form.lab_hours.data, form.theory_hours.data, 
                               form.work_hours.data)
            
            # for course in dtb.get_courses():
            #     if( updatedCourse.id == course.id or updatedCourse.name == course.name):
            #         flash("Course already exists!")
                
            try:
                dtb.update_course(updatedCourse)
                flash("Course has been updated")    
                return redirect(url_for('courses.get_courses'))      
            except Exception as e:
                flash("Error: " + str(e))
                
    return render_template('Update/updateCourse.html', form=form, course=course)

#Delete
@bp.route("/<course_id>/delete/", methods=["GET"])
@login_required
def delete(course_id):
    # try to delete course
    try:
        dtb.delete_course(course_id)
    except oracledb.Error as e:
        flash("Error: " + str(e))
        return redirect(url_for(".get_courses"))

    flash("Course deleted successfully")
    return redirect(url_for('courses.get_courses'))

#Delete an element for specific course
@bp.route('/<course_id>/<int:element_id>/delete/', methods=['GET'])
@login_required
def delete_element_for_course(course_id,element_id):
    try:
        dtb.delete_element_course_bridging(element_id,course_id)
        flash("Element deleted for this course successfully")
        hour_validator(course_id)
    except Exception as e:
        flash("Could not access the record")
        flash("Error: " + str(e))
        return redirect(url_for('courses.list_competencies',course_id=course_id))
    return redirect(url_for('courses.list_competencies',course_id=course_id))

def hour_validator(course_id):
    course=dtb.get_course(course_id)
    total_hours=(course.lab_hours + course.theory_hours) * 15
    current_hours=dtb.get_sum_hours(course_id)
    diff=total_hours-current_hours
    if(diff<0):
        flash(f'You must remove {diff*-1} hours to match {total_hours} hours of {course.name}')
    elif(diff>0):
        flash(f'You must add {diff} hours to match {total_hours} hours of {course.id} {course.name}')

CoursePlannerApp/views/domain_views.py
from flask import Blueprint, redirect, render_template, flash, render_template, request, url_for
from flask_login import login_required
from werkzeug.local import LocalProxy
from CoursePlannerApp.dbmanager import get_db
import oracledb

from CoursePlannerApp.objects.domain import DomainForm, Domain

bp = Blueprint('domains', __name__, url_prefix='/domains')

dtb = LocalProxy(get_db)

#Get * Domains
@bp.route("/")
def get_domains():
    if request.method == 'GET':
        try:
            domains = dtb.get_domains() 
        except Exception as e:
            flash('There is an issue with the Database')
        if not domains or len(domains) == 0:
            flash('There is no course in database')            
        return render_template('domains.html',domains=domains)

@bp.route("/<int:domain_id>/")
def get_domain(domain_id):
    if request.method == 'GET':
        try:
            domain = dtb.get_domain(domain_id) 
        except Exception as e:
            flash('There is an issue with the Database')
        if not domain:
            flash('There is no course in database')            
        return render_template('domain.html', domain=domain)


#Add Domain
@bp.route('/new/', methods=['GET', 'POST'])
@login_required
def create_domain():
    form = DomainForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            
            newDomain = Domain(form.id.data, form.name.data, form.description.data)
            
            for domain in dtb.get_domains():
                if(newDomain.id == domain.id or newDomain.name == domain.name):
                    flash("Domain already exists!")
                
            try:
                dtb.add_domain(newDomain)
                return redirect(url_for('domains.get_domains'))
            
            except oracledb.IntegrityError as e:
                error_obj, = e.args #To acces code error 
                if error_obj.code == 1: # 1 is related to primary key issue (when the primary key already exist) 
                    flash("Domain already exist")
        
            except Exception as e:
                flash("Error: " + str(e))
        else:
            flash('Invalid input')
    return render_template('Add/addDomain.html', form=form)

#Update Domain
@bp.route('/<int:domain_id>/update/', methods=['GET', 'POST'])
@login_required
def update_domain(domain_id):
    
    #Check if domain exist
    try:
        domain = dtb.get_domain(domain_id)
    except Exception as e:
        flash("Error: "+ str(e))
    
    if domain is None:
        flash("Domain not found")
        return redirect(url_for('domains.get_domains'))
    
    form = DomainForm(obj=domain) #Prefill the form
    
    if request.method == 'POST':
        if form.validate_on_submit():

            updatedDomain = Domain(form.id.data, form.name.data, form.description.data)

            for domain in dtb.get_domains():
                if(updatedDomain.id == domain.id or updatedDomain.name == domain.name):
                    flash("Domain already exists!")

            try:
                dtb.update_domain(updatedDomain)
                flash("Domain has been updated")    
                return redirect(url_for('domains.get_domains'))
            except Exception as e:
                flash("Error: " + str(e))

    return render_template('Update/updateDomain.html', form=form, domain=domain)

#Delete
@bp.route("/<domain_id>/delete/", methods=["GET"])
@login_required
def delete(domain_id):

    try:
        courseImpacted = dtb.get_courses_in_domain(domain_id) 
    except Exception as e:
        flash("Could not acces the domain")
        flash("Error: " + str(e))
        return redirect(url_for('domains.get_domains'))

    # try to delete domain
    try:
        dtb.delete_domain(domain_id)
        flash("Domain deleted successfully")
    except oracledb.Error as e:
        flash("You can't delete this domain until you delete the following courses or change their domains")
        courseImpactedString = ""
        for course in courseImpacted:
            courseImpactedString = f'-- {course.name} --'+ courseImpactedString
        flash(courseImpactedString)
    except Exception as e:
        flash("Error: " + str(e))
        return redirect(url_for("domains.get_domains"))

    return redirect(url_for('domains.get_domains'))

CoursePlannerApp/templates/avatar.html
{% extends 'base.html' %}
{% block title %}
    Change Avatar
{% endblock %}
{% block headerTitle %}
    Change your profile details
{% endblock %}
{% block head %}
{% endblock %}
{% block content%}
    <form method="post" enctype="multipart/form-data">
        <h2>Change your profile picture</h2>
        {{ form.csrf_token }}
        {{ form.avatar.label}} {{form.avatar() }}
        <br>
        <button type="submit">Submit</button>
    </form>
    <a href="{{url_for('auth.change_password',email=current_user.email)}}"><button>Change your password</button></a> 
{% endblock%}

CoursePlannerApp/templates/change_avatar.html
{% extends "base.html" %}
{% block head %}
    <title>Avatar</title>
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        <h1>Change your profile picture</h1>
        {{ form.csrf_token }}
        {{ form.avatar() }}
        <button type="submit">Change</button>
    </form>

    <a href="{{ url_for('auth.change_password', email=current_user.email )}}">Change your password</a> 
{% endblock %}

CoursePlannerApp/templates/change_password.html
{% extends "base.html" %}
{% block head %}
    <title>Password</title>
{% endblock %}

{% block content %}
    <form method="POST">
        <h1>Change your password</h1>
        {{ form.csrf_token }}
        {{ form.old_password.label }} {{ form.old_password() }}
        {{ form.new_password.label }} {{ form.new_password() }}
        <br>
        <button type="submit">Change</button>
    </form>

    <a href="{{ url_for('auth.change_avatar', email=current_user.email )}}">Change your avatar</a> 
{% endblock %}

CoursePlannerApp/templates/competency.html
{% extends "base.html" %}
{% block head %}
    <title>Course</title>
{% endblock %}

{% block content%}
    <a href="{{ url_for('elements.create_element') }}"><button>Add an Element to this Competency</button></a>
    <br>
    <main>
        <div class="headings">
            <div class="title">
                <kbd>{{ competency.id }}</kbd>
                <a href="{{ url_for('competencies.list_elements', competency_id=competency.id) }}"><h2>{{ competency.name }}</h2></a>
                <a class="edit" href="{{ url_for('competencies.update_competency', competency_id=competency.id) }}"><i class="fa-solid fa-pen-to-square"></i></a>
                <a class="delete" onclick="return confirm('Deleting this Competency will also delete his Elements. Continue?')" href="{{ url_for('competencies.delete', competency_id=competency.id) }}"><i class="fa-solid fa-trash"></i></a>
            </div>
            <p>{{ competency.achievement }}</p>
        </div>

        <p>Type: {{ competency.type }}</p>

        {% for element in elements %}
            {% if element.competencyId == competency.id %}
                <main style="padding-left: 1rem">
                    <div class="headings">
                        <div class="title">
                            <kbd>{{ competency.id }}_{{ element.order }}</kbd>
                            <h5>{{ element.name }}</h5>
                            <a class="edit" href="{{ url_for('elements.update_element', element_id=element.id) }}"><i class="fa-solid fa-pen-to-square"></i></a>
                            <a class="delete" href="{{ url_for('elements.delete', element_id=element.id) }}"><i class="fa-solid fa-trash"></i></a>
                        </div>
                        <p>{{ element.criteria }}</p>
                    </div>
                </main>
            {% endif %}
        {% endfor %}
    </main>
{% endblock%}

CoursePlannerApp/templates/course.html
{% extends "base.html" %}
{% block head %}
    <title>Course</title>
{% endblock %}

{% block content%}
    <a href="{{ url_for('courses.add_element_for_course',course_id=course.id) }}"><button>Add a new element for this course</button></a>
    <br>
    <main>
        <div class="headings">
            <div class="title">
                <kbd>{{ course.id }}</kbd>
                <a href="{{ url_for('courses.list_competencies', course_id=course.id) }}"><h1>{{ course.name }}</h1></a>
                <a class="edit" href="{{ url_for('courses.update_course', course_id=course.id )}}"><i class="fa-solid fa-pen-to-square"></i></a>
                <a class="delete" href="{{ url_for('courses.delete', course_id=course.id )}}"><i class="fa-solid fa-trash"></i></a>
            </div>
            <p>{{ course.description }}</p>
        </div>

        {% for domain in domains %}
            {% if domain.id == course.domainId %}
                <p>Domain: <a href="{{ url_for('domains.get_domain', domain_id=domain.id) }}">{{ domain.name }}</a></p>
            {% endif %}
        {% endfor %}

        <div class="grid">
            <p>Term: {{ course.termId }}</p>
            <p>Class hours: {{ course.theory_hours }}</p>
            <p>Lab hours: {{ course.lab_hours }}</p>
            <p>Homework hours: {{ course.work_hours }}</p>
            <p>Total hours: {{ (course.lab_hours + course.theory_hours) * 15}}</p>
            <p>Credits: {{ ((course.lab_hours + course.theory_hours + course.work_hours) / 3) | round(2) }}</p>
        </div>
    </main>
    {% for competency in competencies %}
        <main style="padding-left: 1rem">
            <div class="headings">
                <div class="title">
                    <kbd>{{ competency.id }}</kbd>
                    <a href="{{ url_for('competencies.list_elements', competency_id=competency.id) }}"><h2>{{ competency.name }}</h2></a>
                    <a class="edit" href="{{ url_for('competencies.update_competency', competency_id=competency.id) }}"><i class="fa-solid fa-pen-to-square"></i></a>
                    <a class="delete" onclick="return confirm('Deleting this Competency will also delete his Elements. Continue?')" href="{{ url_for('competencies.delete', competency_id=competency.id) }}"><i class="fa-solid fa-trash"></i></a>
                </div>
                <p>{{ competency.achievement }}</p>
            </div>

            <p>Type: {{ competency.type }}</p>

            {% for element in elements_covered %}
                {% if element.competencyId == competency.id %}
                    <main style="padding-left: 1rem">
                        <div class="headings">
                            <div class="title">
                                <kbd>{{ competency.id }}_{{ element.order }}</kbd>
                                <h5>{{ element.name }}</h5>
                                <a class="edit" href="{{ url_for('elements.update_element', element_id=element.id) }}"><i class="fa-solid fa-pen-to-square"></i></a>
                                <a class="delete" href="{{ url_for('courses.delete_element_for_course', element_id=element.id, course_id=course.id) }}"><i class="fa-solid fa-trash"></i></a>
                            </div>
                            <p>{{ element.criteria }}</p>
                        </div>
                    </main>
                {% endif %}
            {% endfor %}
        </main>
        <hr>
    {% endfor %}
{% endblock%}

CoursePlannerApp/templates/courses.html
{% extends "base.html" %}
{% block head %}
    <title>Course List</title>
{% endblock %}

{% block content%}
    <input type="text" name="filter" placeholder="Filter">
    <a href="{{ url_for('courses.create_course') }}"><button>Add Course</button></a>
    <br>
    {% for course in courses %}
        <main class="searchable">
            <div class="headings">
                <div class="title">
                    <kbd>{{ course.id }}</kbd>
                    <a href="{{ url_for('courses.list_competencies', course_id=course.id) }}"><h1>{{ course.name }}</h1></a>
                    <a class="edit" href="{{ url_for('courses.update_course', course_id=course.id )}}"><i class="fa-solid fa-pen-to-square"></i></a>
                    <a class="delete" href="{{ url_for('courses.delete', course_id=course.id )}}"><i class="fa-solid fa-trash"></i></a>
                </div>
                <p>{{ course.description }}</p>
            </div>

            {% for domain in domains %}
                {% if domain.id == course.domainId %}
                    <p>Domain: <a href="{{ url_for('domains.get_domain', domain_id=domain.id) }}">{{ domain.name }}</a></p>
                {% endif %}
            {% endfor %}

            <div class="grid">
                <p>Term: {{ course.termId }}</p>
                <p>Class hours: {{ course.theory_hours }}</p>
                <p>Lab hours: {{ course.lab_hours }}</p>
                <p>Homework hours: {{ course.work_hours }}</p>
                <p>Total hours: {{ (course.lab_hours + course.theory_hours) * 15}}</p>
                <p>Credits: {{ ((course.lab_hours + course.theory_hours + course.work_hours) / 3) | round(2) }}</p>
            </div>
        </main>
        <hr>
    {% endfor %}
{% endblock%}

CoursePlannerApp/templates/custom404.html
{% extends "base.html" %}
{% block head %}
    <title>Not Found</title>
{% endblock %}

{% block content %}
    <h1>Sorry, the page you are looking for does not exist.</h1>
{% endblock %}

CoursePlannerApp/templates/domain.html
{% extends "base.html" %}
{% block head %}
    <title>Domain</title>
{% endblock %}

{% block content %}
    <main>
        <div class="headings">
            <div class="title">
                <h2>{{ domain.name }}</h2>
                <a class="edit" href="{{ url_for('domains.update_domain', domain_id=domain.id) }}"><i class="fa-solid fa-pen-to-square"></i></a>
                <a class="delete" href="{{ url_for('domains.delete', domain_id=domain.id) }}"><i class="fa-solid fa-trash"></i></a>
            </div>
            <p>{{ domain.description }}</p>
        </div>
    </main>
{% endblock%}

CoursePlannerApp/templates/groups.html
{% extends "base.html" %}
{% block title %}
    Organizer - Group List
{% endblock %}

{% block head %}
    <script defer type="text/javascript" src="{{ url_for('static', filename='groups.js')}}"></script>
{% endblock %}

{% block content%}
    <main id="header" class="container-fluid">
        <h1>Groups</h1>
        {% if manages %} <button class="add">Add Group</button> {% endif %}
    </main>

    <div>
        <table>
            <tbody>
                {% for group in groups %}
                    <tr data-group-id="{{ group.id }}" data-group-name="{{ group.name }}">
                        <td>{{ group.name }}</td>

                        <td class="buttons">
                            {% if group.id not in [0, 1, 2] %}
                                <button class="edit">Edit</button>
                                <button class="delete">Delete</button>
                            {% else %}
                                <button class="secondary" disabled>Edit</button>
                                <button class="secondary" disabled>Delete</button>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- multipurpose popup form -->
    <main class="container-fluid overlay">
        <button class="close">🗙</button>
        <form method="POST">
            {{ form.csrf_token }}
            {{ form.hidden_tag() }}
            {{ form.name.label }} {{ form.name() }}
            <input name="id" type="hidden" value=-1>
            <button type="submit"></button>
        </form>
    </main>
{% endblock%}

CoursePlannerApp/templates/home.html
{% extends 'base.html' %}

{% block title %}
    Course Planner
{% endblock %}

{% block head %}
    <script defer type="text/javascript" src="{{ url_for('static', filename='courses.js')}}"></script>
{% endblock %}

{% block headerTitle %}
    Courses List
{% endblock %}

{% block content%}
    <ul>
        {% for course in courses %}
            <li>
                <a href="{{ url_for('courses.list_competencies', course_id=course.id) }}">{{course.name | safe}}</a>
                <p>{{course.description | safe}}</p>
                {% if course.termId%2==0 %}
                    <p>Session: Winter</p>
                    {%else%}
                        <p>Session: Fall</p>
                {% endif %}
                <p>Term: {{course.termId | safe}}</p>
                <p>Class hours: {{course.theory_hours | safe}}</p>
                <p>Lab hours: {{course.lab_hours | safe}}</p>
                <p>Homework hours: {{course.work_hours | safe}}</p>
                {% for domain in domains %}
                    {% if domain.id==course.domainId %}
                        <p>Domain: <a href="{{url_for('courses.get_domain',domain_id=domain.id,course_id=course.id)}}">{{domain.name | safe}}</a></p>
                    {% endif %}
                {% endfor %}
                <p>Total hours: {{(course.lab_hours+course.theory_hours)*15}}</p>
                <p>Credits: {{(course.lab_hours+course.theory_hours+course.work_hours)/3}}</p>
            </li>
            <hr>
        {% endfor %}
    </ul>
{% endblock%}

CoursePlannerApp/templates/login.html
{% extends "base.html" %}
{% block content %}
    <form method="POST">
        {{ form.csrf_token }}
        {{ form.email.label }} {{ form.email() }}
        {{ form.password.label }} {{ form.password() }}
        <span>{{ form.remember_me.label }} {{ form.remember_me() }}</span>
        <br>
        <button type="submit">Login</button>
    </form>
{% endblock %}

CoursePlannerApp/templates/signup.html
{% extends "base.html" %}
{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {{ form.csrf_token }}
        {{ form.email.label}} {{ form.email() }}
        {{ form.password.label}} {{ form.password() }}
        {{ form.name.label}} {{ form.name() }}
        {{ form.avatar.label}} {{ form.avatar() }}
        <br>
        <button type="submit">Signup</button>
    </form>
{% endblock %}